apiVersion: v1
kind: ConfigMap
metadata:
  name: genius-game-config
  namespace: genius-games
data:
  # Game configuration
  game.config.yaml: |
    games:
      minority_game:
        min_players: 3
        max_players: 100
        rounds: 20
        time_limit_ms: 5000
      byzantine_generals:
        min_players: 4
        max_players: 50
        traitor_percentage: 0.33
      prisoners_dilemma:
        min_players: 2
        max_players: 100
        rounds: 10
      battle_royale:
        min_players: 10
        max_players: 100
        map_size: 20
        zone_shrink_rate: 2
      
    # AI Provider settings
    ai_providers:
      openai:
        enabled: true
        models:
          - gpt-4-turbo-preview
          - gpt-3.5-turbo
        rate_limit: 100
      anthropic:
        enabled: true
        models:
          - claude-3-opus
          - claude-3-sonnet
        rate_limit: 50
      ollama:
        enabled: true
        endpoint: http://ollama-service.genius-games.svc.cluster.local:11434
        models:
          - llama2
          - mistral
          - josiefied-qwen3:0.6b-q4_0
    
    # Server settings
    server:
      max_concurrent_games: 1000
      max_players_per_game: 100
      websocket_timeout_ms: 300000
      enable_metrics: true
      enable_tracing: true
  
  # Prometheus metrics config
  prometheus.yaml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'genius-game-server'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: genius-game-server