apiVersion: apps/v1
kind: Deployment
metadata:
  name: genius-game-server
  namespace: genius-games
  labels:
    app: genius-game-server
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: genius-game-server
  template:
    metadata:
      labels:
        app: genius-game-server
        version: v1
    spec:
      containers:
      - name: game-server
        image: ghcr.io/2lab-ai/genius-game-server:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: websocket
          containerPort: 8081
          protocol: TCP
        env:
        - name: RUST_LOG
          value: "info"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: "8080"
        - name: WS_PORT
          value: "8081"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: genius-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: genius-secrets
              key: redis-url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: genius-secrets
              key: openai-api-key
              optional: true
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: genius-secrets
              key: anthropic-api-key
              optional: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: game-data
          mountPath: /app/data
      volumes:
      - name: game-data
        persistentVolumeClaim:
          claimName: genius-game-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genius-game-data-pvc
  namespace: genius-games
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard