# DO NOT COMMIT THIS FILE WITH ACTUAL SECRETS
# Copy this file to secrets.yaml and fill in the actual values
# Add secrets.yaml to .gitignore

apiVersion: v1
kind: Secret
metadata:
  name: genius-secrets
  namespace: genius-games
type: Opaque
stringData:
  # Database connection
  database-url: "postgresql://genius:YOUR_DB_PASSWORD@postgres-service:5432/genius_games"
  
  # Redis connection
  redis-url: "redis://redis-service:6379"
  
  # AI Provider API Keys
  openai-api-key: "sk-YOUR_OPENAI_API_KEY"
  anthropic-api-key: "sk-ant-YOUR_ANTHROPIC_API_KEY"
  
  # AWS Credentials (for Bedrock)
  aws-access-key-id: "YOUR_AWS_ACCESS_KEY"
  aws-secret-access-key: "YOUR_AWS_SECRET_KEY"
  
  # Authentication secrets
  jwt-secret: "YOUR_STRONG_JWT_SECRET"
  
  # Monitoring
  grafana-admin-password: "YOUR_GRAFANA_PASSWORD"